version: '3.0'
networks:
  dockertest:
services:
  env-calcula-juros:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-calcula-juros
    image: api-calcula-juros-imagem:latest    
    ports: 
        - "5008:80"    
    networks: 
        - dockertest